// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADqEpcDfgMCeBszqHndJF4uABi3kre-sA',
    appId: '1:891990241393:web:af02f9dab3147a9f286bd0',
    messagingSenderId: '891990241393',
    projectId: 'notesapp-80',
    authDomain: 'notesapp-80.firebaseapp.com',
    storageBucket: 'notesapp-80.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI9rsSc6GTdh6TF6-eYsgqR4_tSgButmE',
    appId: '1:891990241393:android:2a6bb261634f2b17286bd0',
    messagingSenderId: '891990241393',
    projectId: 'notesapp-80',
    storageBucket: 'notesapp-80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo4eMYOwO8DjbKnUBV0VBHD-kxXM-aHrU',
    appId: '1:891990241393:ios:5a13910c8a897fd7286bd0',
    messagingSenderId: '891990241393',
    projectId: 'notesapp-80',
    storageBucket: 'notesapp-80.appspot.com',
    iosBundleId: 'lt.robertasmdev.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo4eMYOwO8DjbKnUBV0VBHD-kxXM-aHrU',
    appId: '1:891990241393:ios:5a13910c8a897fd7286bd0',
    messagingSenderId: '891990241393',
    projectId: 'notesapp-80',
    storageBucket: 'notesapp-80.appspot.com',
    iosBundleId: 'lt.robertasmdev.notesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADqEpcDfgMCeBszqHndJF4uABi3kre-sA',
    appId: '1:891990241393:web:da1ea06de9564b63286bd0',
    messagingSenderId: '891990241393',
    projectId: 'notesapp-80',
    authDomain: 'notesapp-80.firebaseapp.com',
    storageBucket: 'notesapp-80.appspot.com',
  );
}
